name: mobile_app
description: MirrorMind - AI Career Prediction Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  dio: ^5.4.0

  # Secure storage for JWT
  flutter_secure_storage: ^9.0.0

  # State management
  provider: ^6.1.2

  # Google Fonts (Inter)
  google_fonts: ^6.2.1

  # Image handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # File picker (for certificates PDF)
  file_picker: ^8.0.3

  # Charts
  fl_chart: ^0.68.0

  # Animations
  lottie: ^3.1.0

  # HTTP multipart upload to Cloudinary
  http: ^1.2.1
  http_parser: ^4.0.2

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-logo.jpeg"
