"""Add History columns

Revision ID: 076ca1ab6fa7
Revises: 3adf66b74da7
Create Date: 2026-07-27 16:16:09.202508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076ca1ab6fa7'
down_revision: Union[str, None] = '3adf66b74da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_logs', sa.Column('code_context', sa.String(), nullable=True))
    op.add_column('error_logs', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('error_logs', sa.Column('hidden_by_user', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error_logs', 'hidden_by_user')
    op.drop_column('error_logs', 'resolved_at')
    op.drop_column('error_logs', 'code_context')
    # ### end Alembic commands ###
