"""Add Gemini columns to ErrorLog

Revision ID: 3adf66b74da7
Revises: a9f3b81c2d44
Create Date: 2026-07-27 15:53:27.811220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3adf66b74da7'
down_revision: Union[str, None] = 'a9f3b81c2d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_logs', sa.Column('hint', sa.String(), nullable=True))
    op.add_column('error_logs', sa.Column('corrected_block', sa.String(), nullable=True))
    op.add_column('error_logs', sa.Column('explanation', sa.String(), nullable=True))
    op.add_column('error_logs', sa.Column('gemini_fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error_logs', 'gemini_fetched_at')
    op.drop_column('error_logs', 'explanation')
    op.drop_column('error_logs', 'corrected_block')
    op.drop_column('error_logs', 'hint')
    # ### end Alembic commands ###
