"""Add avatar_url and thumbnail_url

Revision ID: 4b1b752a9411
Revises: ad13c8c86331
Create Date: 2026-07-24 21:11:37.635339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1b752a9411'
down_revision: Union[str, None] = 'ad13c8c86331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('projects', 'thumbnail_url')
    # ### end Alembic commands ###
