"""Split student profile

Revision ID: ad13c8c86331
Revises: 
Create Date: 2026-07-24 20:41:29.750008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad13c8c86331'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Integer(), nullable=True),
    sa.Column('certificate_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internships_student_id'), 'internships', ['student_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('live_demo_url', sa.String(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_student_id'), 'projects', ['student_id'], unique=False)
    op.create_table('semester_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('sgpa', sa.Float(), nullable=False),
    sa.Column('credits_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semester_records_student_id'), 'semester_records', ['student_id'], unique=False)
    op.create_table('subject_marks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('semester_record_id', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['semester_record_id'], ['semester_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_marks_semester_record_id'), 'subject_marks', ['semester_record_id'], unique=False)
    op.drop_column('students', 'cgpa')
    op.drop_column('students', 'projects_count')
    op.drop_column('students', 'internship_domain')
    op.drop_column('students', 'internship_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('internship_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('internship_domain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('projects_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subject_marks_semester_record_id'), table_name='subject_marks')
    op.drop_table('subject_marks')
    op.drop_index(op.f('ix_semester_records_student_id'), table_name='semester_records')
    op.drop_table('semester_records')
    op.drop_index(op.f('ix_projects_student_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_internships_student_id'), table_name='internships')
    op.drop_table('internships')
    # ### end Alembic commands ###
